// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5LXBWKS4EwzbjbcBb3NmStRqOHrR55Pc',
    appId: '1:562676447347:web:669979463409436e4b5206',
    messagingSenderId: '562676447347',
    projectId: 'iron-body-ca427',
    authDomain: 'iron-body-ca427.firebaseapp.com',
    storageBucket: 'iron-body-ca427.appspot.com',
    measurementId: 'G-KW5Q8GBJLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyIXXQNiWnT98nGFLaLkdNt8BpzP1re-o',
    appId: '1:562676447347:android:229e5a3c9f4bc8554b5206',
    messagingSenderId: '562676447347',
    projectId: 'iron-body-ca427',
    storageBucket: 'iron-body-ca427.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBpoGlvbDa6Idn0_OYH-jf3vFBHzCs1bU',
    appId: '1:562676447347:ios:1dc735d55a2e095c4b5206',
    messagingSenderId: '562676447347',
    projectId: 'iron-body-ca427',
    storageBucket: 'iron-body-ca427.appspot.com',
    androidClientId: '562676447347-1ah6dgg2lm8gell7g4r4atdd30tt3h42.apps.googleusercontent.com',
    iosClientId: '562676447347-u6up57ub8pvr77mir263j4r66ubdum51.apps.googleusercontent.com',
    iosBundleId: 'com.example.appiron',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBpoGlvbDa6Idn0_OYH-jf3vFBHzCs1bU',
    appId: '1:562676447347:ios:1dc735d55a2e095c4b5206',
    messagingSenderId: '562676447347',
    projectId: 'iron-body-ca427',
    storageBucket: 'iron-body-ca427.appspot.com',
    androidClientId: '562676447347-1ah6dgg2lm8gell7g4r4atdd30tt3h42.apps.googleusercontent.com',
    iosClientId: '562676447347-u6up57ub8pvr77mir263j4r66ubdum51.apps.googleusercontent.com',
    iosBundleId: 'com.example.appiron',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5LXBWKS4EwzbjbcBb3NmStRqOHrR55Pc',
    appId: '1:562676447347:web:30f451e8f2b43f7f4b5206',
    messagingSenderId: '562676447347',
    projectId: 'iron-body-ca427',
    authDomain: 'iron-body-ca427.firebaseapp.com',
    storageBucket: 'iron-body-ca427.appspot.com',
    measurementId: 'G-73QFCVWB74',
  );

}