name: iron
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  logger: ^1.1.0
  table_calendar: ^3.0.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.1
  image_picker: ^0.8.4+6
  google_fonts: ^4.0.4
  cloud_firestore: ^4.17.5
  flutter_facebook_auth: ^5.0.0
  flutter_login_facebook: ^2.0.1
  flutter_spinkit: ^5.1.0
  flutter_bloc: ^8.1.3
  camera: ^0.10.5+2
  path: ^1.8.3
  path_provider: ^2.0.15
  lottie: ^2.6.0
  google_mlkit_pose_detection: ^0.12.0
  firebase_storage: ^11.4.2
  shared_preferences: ^2.0.11
  video_player: ^2.5.2
  font_awesome_flutter: ^10.2.0
  mailer: ^6.0.0
  provider: ^6.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - images/facebook.png
    - images/google.png
    - images/1.png
    - images/2.png
    - images/3.png
    - images/4.png
    - images/5.png
    - images/6.png
    - images/7.png
    - images/8.png
    - images/9.png
    - images/LEG.png
    - images/HAND.png
    - images/ABDOMEN.png
    - images/BEHIND.png
    - images/BREAST.png
    - images/superman_hold.png
    - images/plank.png
    - images/squat.png
    - lib/l10n/app_en.arb
    - lib/l10n/app_th.arb
